node {
    stage('checkout'){
        checkout(
            [$class: 'GitSCM', 
            branches: [[name: '*/main']], 
            extensions: [], 
            userRemoteConfigs: [[credentialsId: 'github_token',
            url: 'https://github.com/sebastian2296/devops-project.git']]])
        sh 'ls'
    }
}